version: '3.9'
services:
  frontend:
    container_name: todo_frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
  backend:
    container_name: todo_backend
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    volumes:
      - ./backend/src:/app-backend/src
    depends_on:
      - db

    env_file:
      - ./backend/.env
  db:
    image: mysql:8.0.32
    container_name: todo_db
    ports:
      - 3306:3306
    env_file:
      - .env
    restart: 'always'
